<?php

namespace Database\Seeders;

use App\Support\DocumentTermCodes;
use App\Support\DomainStatus;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class DemoProcurementFlowSeeder extends Seeder
{
    private array $columnCache = [];

    public function run(): void
    {
        if (! $this->hasRequiredTables()) {
            return;
        }

        DB::transaction(function (): void {
            $this->cleanupPreviousDemoRows();

            $userId = $this->firstId('users');
            $supplierIds = $this->resolveSupplierIds(12, $userId);
            $itemIds = $this->resolveItemIds(40, $userId);

            $shipmentSequence = 1;
            $receiptSequence = 1;

            for ($poIndex = 1; $poIndex <= 100; $poIndex++) {
                $supplierId = $supplierIds->random();
                $poDate = Carbon::today()->subDays(140 - $poIndex);
                $etaDate = (clone $poDate)->addDays(random_int(10, 35));
                $poNumber = sprintf('DEMO-PO-%04d', $poIndex);

                $lineCount = random_int(2, 5);
                $lineRows = [];
                $poStatus = DocumentTermCodes::PO_OPEN;

                for ($line = 1; $line <= $lineCount; $line++) {
                    $itemId = $itemIds->random();
                    $orderedQty = random_int(25, 180);
                    $mode = $this->lineMode($poIndex, $line);

                    [$receivedQty, $outstandingQty, $itemStatus, $etdDate, $etaLineDate] = $this->lineMetrics(
                        $mode,
                        $orderedQty,
                        $etaDate
                    );

                    if ($itemStatus === DocumentTermCodes::ITEM_LATE) {
                        $poStatus = DocumentTermCodes::PO_LATE;
                    } elseif ($poStatus !== DocumentTermCodes::PO_LATE && $itemStatus !== DocumentTermCodes::ITEM_CLOSED) {
                        $poStatus = $poIndex % 4 === 0
                            ? DocumentTermCodes::PO_ISSUED
                            : DocumentTermCodes::PO_OPEN;
                    }

                    $lineRows[] = [
                        'item_id' => $itemId,
                        'ordered_qty' => $orderedQty,
                        'received_qty' => $receivedQty,
                        'outstanding_qty' => $outstandingQty,
                        'item_status' => $itemStatus,
                        'etd_date' => $etdDate?->toDateString(),
                        'eta_date' => $etaLineDate?->toDateString(),
                        'unit_price' => random_int(15000, 450000),
                        'remark' => 'Demo line ' . $line,
                    ];
                }

                if (collect($lineRows)->every(fn (array $row) => (float) $row['outstanding_qty'] <= 0)) {
                    $poStatus = DocumentTermCodes::PO_CLOSED;
                }

                $poId = DB::table('purchase_orders')->insertGetId($this->row('purchase_orders', [
                    'supplier_id' => $supplierId,
                    'po_number' => $poNumber,
                    'po_date' => $poDate->toDateString(),
                    'eta_date' => $etaDate->toDateString(),
                    'currency' => 'IDR',
                    'remark' => 'Demo PO generated by DemoProcurementFlowSeeder',
                    'created_by' => $userId,
                ] + DomainStatus::payload(DomainStatus::GROUP_PO_STATUS, 'status', $poStatus)));

                $poItemIds = [];
                foreach ($lineRows as $lineRow) {
                    $poItemIds[] = DB::table('purchase_order_items')->insertGetId($this->row('purchase_order_items', array_merge($lineRow, [
                        'purchase_order_id' => $poId,
                    ], DomainStatus::payload(DomainStatus::GROUP_PO_ITEM_STATUS, 'item_status', $lineRow['item_status']))));
                }

                if ($poIndex > 82) {
                    continue;
                }

                $shipmentStatus = $this->shipmentStatusForIndex($poIndex);
                $shipmentDate = (clone $poDate)->addDays(random_int(4, 18));
                $shipmentId = DB::table('shipments')->insertGetId($this->row('shipments', [
                    'purchase_order_id' => $poId,
                    'supplier_id' => $supplierId,
                    'shipment_number' => sprintf('DEMO-SHP-%04d', $shipmentSequence++),
                    'shipment_date' => $shipmentDate->toDateString(),
                    'delivery_note_number' => sprintf('DN-DEMO-%04d', $poIndex),
                    'invoice_number' => sprintf('INV-DEMO-%04d', $poIndex),
                    'invoice_date' => $shipmentDate->toDateString(),
                    'invoice_currency' => 'IDR',
                    'supplier_remark' => 'Demo shipment for ' . $poNumber,
                    'created_by' => $userId,
                ] + DomainStatus::payload(DomainStatus::GROUP_SHIPMENT_STATUS, 'status', $shipmentStatus)));

                $shipmentItems = [];
                foreach ($poItemIds as $offset => $poItemId) {
                    $lineRow = $lineRows[$offset];
                    $shippedQty = match ($shipmentStatus) {
                        DocumentTermCodes::SHIPMENT_DRAFT => max(1, (int) ceil($lineRow['ordered_qty'] * 0.5)),
                        default => $lineRow['ordered_qty'],
                    };

                    $receivedOnShipment = match ($shipmentStatus) {
                        DocumentTermCodes::SHIPMENT_RECEIVED => $shippedQty,
                        DocumentTermCodes::SHIPMENT_PARTIAL_RECEIVED => max(0, (int) floor($shippedQty * 0.65)),
                        default => 0,
                    };

                    $shipmentItemId = DB::table('shipment_items')->insertGetId($this->row('shipment_items', [
                        'shipment_id' => $shipmentId,
                        'purchase_order_item_id' => $poItemId,
                        'shipped_qty' => $shippedQty,
                        'received_qty' => $receivedOnShipment,
                        'invoice_unit_price' => $lineRow['unit_price'],
                    ]));

                    $shipmentItems[] = [
                        'shipment_item_id' => $shipmentItemId,
                        'purchase_order_item_id' => $poItemId,
                        'received_qty' => $receivedOnShipment,
                    ];
                }

                if (! in_array($shipmentStatus, [
                    DocumentTermCodes::SHIPMENT_PARTIAL_RECEIVED,
                    DocumentTermCodes::SHIPMENT_RECEIVED,
                ], true)) {
                    continue;
                }

                $receiptId = DB::table('goods_receipts')->insertGetId($this->row('goods_receipts', [
                    'purchase_order_id' => $poId,
                    'shipment_id' => $shipmentId,
                    'gr_number' => sprintf('DEMO-GR-%04d', $receiptSequence++),
                    'receipt_date' => (clone $shipmentDate)->addDays(random_int(1, 6))->toDateString(),
                    'document_number' => sprintf('GRDOC-DEMO-%04d', $poIndex),
                    'note' => 'Demo goods receipt for ' . $poNumber,
                    'created_by' => $userId,
                ] + DomainStatus::payload(DomainStatus::GROUP_GOODS_RECEIPT_STATUS, 'status', DocumentTermCodes::GR_POSTED)));

                if (! Schema::hasTable('goods_receipt_items')) {
                    continue;
                }

                foreach ($shipmentItems as $shipmentItem) {
                    if ((float) $shipmentItem['received_qty'] <= 0) {
                        continue;
                    }

                    DB::table('goods_receipt_items')->insert($this->row('goods_receipt_items', [
                        'goods_receipt_id' => $receiptId,
                        'shipment_id' => $shipmentId,
                        'shipment_item_id' => $shipmentItem['shipment_item_id'],
                        'purchase_order_item_id' => $shipmentItem['purchase_order_item_id'],
                        'received_qty' => $shipmentItem['received_qty'],
                        'note' => 'Demo GR item',
                    ]));
                }
            }
        });
    }

    private function hasRequiredTables(): bool
    {
        foreach (['purchase_orders', 'purchase_order_items', 'shipments', 'shipment_items', 'goods_receipts'] as $table) {
            if (! Schema::hasTable($table)) {
                return false;
            }
        }

        return true;
    }

    private function cleanupPreviousDemoRows(): void
    {
        $poIds = DB::table('purchase_orders')
            ->where('po_number', 'like', 'DEMO-PO-%')
            ->pluck('id');

        $shipmentIds = DB::table('shipments')
            ->where('shipment_number', 'like', 'DEMO-SHP-%')
            ->pluck('id');

        $receiptIds = DB::table('goods_receipts')
            ->where('gr_number', 'like', 'DEMO-GR-%')
            ->pluck('id');

        if (Schema::hasTable('goods_receipt_items') && $receiptIds->isNotEmpty()) {
            DB::table('goods_receipt_items')->whereIn('goods_receipt_id', $receiptIds)->delete();
        }

        if ($receiptIds->isNotEmpty()) {
            DB::table('goods_receipts')->whereIn('id', $receiptIds)->delete();
        }

        if ($shipmentIds->isNotEmpty()) {
            DB::table('shipment_items')->whereIn('shipment_id', $shipmentIds)->delete();
            DB::table('shipments')->whereIn('id', $shipmentIds)->delete();
        }

        if ($poIds->isNotEmpty()) {
            DB::table('purchase_order_items')->whereIn('purchase_order_id', $poIds)->delete();
            DB::table('purchase_orders')->whereIn('id', $poIds)->delete();
        }
    }

    private function resolveSupplierIds(int $targetCount, ?int $userId): Collection
    {
        $supplierIds = DB::table('suppliers')->pluck('id');

        $missing = max(0, $targetCount - $supplierIds->count());
        for ($i = 1; $i <= $missing; $i++) {
            $supplierIds->push(DB::table('suppliers')->insertGetId($this->row('suppliers', [
                'supplier_name' => sprintf('Demo Supplier %02d', $i),
                'supplier_code' => sprintf('SUPD%02d', $i),
                'address' => 'Demo supplier address ' . $i,
                'email' => sprintf('demo-supplier-%02d@example.test', $i),
                'phone' => '08120000' . str_pad((string) $i, 2, '0', STR_PAD_LEFT),
                'status' => true,
                'created_by' => $userId,
            ])));
        }

        return DB::table('suppliers')->pluck('id');
    }

    private function resolveItemIds(int $targetCount, ?int $userId): Collection
    {
        $itemIds = DB::table('items')->pluck('id');

        $unitId = $this->firstId('units');
        $categoryId = $this->firstId('item_categories');

        $missing = max(0, $targetCount - $itemIds->count());
        for ($i = 1; $i <= $missing; $i++) {
            $itemIds->push(DB::table('items')->insertGetId($this->row('items', [
                'item_code' => sprintf('DEMO-ITEM-%03d', $i),
                'item_name' => sprintf('Demo Item %03d', $i),
                'description' => 'Demo item generated by seeder',
                'unit_id' => $unitId,
                'item_category_id' => $categoryId,
                'category_id' => $categoryId,
                'status' => true,
                'created_by' => $userId,
            ])));
        }

        return DB::table('items')->pluck('id');
    }

    private function lineMode(int $poIndex, int $line): string
    {
        $bucket = ($poIndex + $line) % 10;

        return match (true) {
            $bucket <= 1 => 'waiting',
            $bucket <= 4 => 'confirmed',
            $bucket <= 6 => 'late',
            $bucket <= 8 => 'partial',
            default => 'closed',
        };
    }

    private function lineMetrics(string $mode, int $orderedQty, Carbon $etaDate): array
    {
        return match ($mode) {
            'waiting' => [
                0,
                $orderedQty,
                DocumentTermCodes::ITEM_WAITING,
                null,
                (clone $etaDate)->addDays(random_int(2, 10)),
            ],
            'confirmed' => [
                0,
                $orderedQty,
                DocumentTermCodes::ITEM_CONFIRMED,
                (clone $etaDate)->subDays(random_int(1, 4)),
                (clone $etaDate)->addDays(random_int(2, 7)),
            ],
            'late' => [
                0,
                $orderedQty,
                DocumentTermCodes::ITEM_LATE,
                Carbon::today()->subDays(random_int(3, 20)),
                Carbon::today()->subDays(random_int(1, 8)),
            ],
            'partial' => (function () use ($orderedQty, $etaDate) {
                $receivedQty = max(1, (int) floor($orderedQty * random_int(20, 70) / 100));

                return [
                    $receivedQty,
                    $orderedQty - $receivedQty,
                    DocumentTermCodes::ITEM_PARTIAL,
                    (clone $etaDate)->addDays(random_int(1, 5)),
                    (clone $etaDate)->addDays(random_int(4, 9)),
                ];
            })(),
            default => [
                $orderedQty,
                0,
                DocumentTermCodes::ITEM_CLOSED,
                (clone $etaDate)->subDays(random_int(2, 6)),
                (clone $etaDate)->subDays(random_int(1, 3)),
            ],
        };
    }

    private function shipmentStatusForIndex(int $poIndex): string
    {
        return match ($poIndex % 4) {
            0 => DocumentTermCodes::SHIPMENT_RECEIVED,
            1 => DocumentTermCodes::SHIPMENT_PARTIAL_RECEIVED,
            2 => DocumentTermCodes::SHIPMENT_SHIPPED,
            default => DocumentTermCodes::SHIPMENT_DRAFT,
        };
    }

    private function row(string $table, array $values): array
    {
        $columns = $this->columns($table);
        $row = [];

        foreach ($values as $column => $value) {
            if (in_array($column, $columns, true)) {
                $row[$column] = $value;
            }
        }

        if (in_array('created_at', $columns, true) && ! array_key_exists('created_at', $row)) {
            $row['created_at'] = now();
        }

        if (in_array('updated_at', $columns, true) && ! array_key_exists('updated_at', $row)) {
            $row['updated_at'] = now();
        }

        return $row;
    }

    private function columns(string $table): array
    {
        if (! array_key_exists($table, $this->columnCache)) {
            $this->columnCache[$table] = Schema::getColumnListing($table);
        }

        return $this->columnCache[$table];
    }

    private function firstId(string $table): ?int
    {
        if (! Schema::hasTable($table)) {
            return null;
        }

        $id = DB::table($table)->value('id');

        return $id !== null ? (int) $id : null;
    }
}
